### PR TITLE
Crop image

### PR DESCRIPTION
**Pull request by deldesir**

### CODE REVIEW

**Comment by holta** [comment]
This seems to require... ?

```
apt install libcairo2-dev libgirepository1.0-dev libexiv2-dev libgexiv2-dev python3-dev
cd /usr/local/calibre-web-py3
source bin/activate
pip3 install smartcrop pillow
```

The final 2 (smartcrop, pillow) should probably be added to:

https://github.com/deldesir/calibre-web/blob/main/requirements.txt

**Comment by holta** [comment]
Code changes (including CSS like this below) need to be within PR's — so others can understand + help:

- https://github.com/deldesir/calibre-web/commit/45726c6c6f466759ff47c5f92273f8161376a250

Whereas doc changes (e.g. typo quick fixes!) do not need a full PR.

**Comment by holta** [comment]
@deldesir the following Multipass clout-init script [ e.g. omg.yml ] completes (install works!) but then functional testing fails (http://box/books shows **"502 Bad Gateway"**)

```
runcmd:
  - apt update
  - export DEBIAN_FRONTEND=noninteractive
  - apt install libcairo2-dev libgirepository1.0-dev libexiv2-dev libgexiv2-dev python3-dev -y
  - mkdir /etc/iiab
  - |
    cat >> /etc/iiab/local_vars.yml <<EOF
    calibreweb_install: True
    calibreweb_enabled: True
    calibreweb_repo_url: https://github.com/deldesir/calibre-web
    calibreweb_version: main
    kalite_install: False
    kalite_enabled: False
    kiwix_install: False
    kiwix_enabled: False
    osm_vector_maps_install: False
    awstats_install: False
    awstats_enabled: False
    matomo_install: False
    matomo_enabled: False
    captiveportal_install: False
    admin_console_install: False
    admin_console_enabled: False
    EOF
  - curl iiab.io/risky.txt | bash &
  ```

Please help by refining https://github.com/deldesir/calibre-web/blob/main/requirements.txt and/or LMK what else is needed?

**Comment by holta** [comment]
Just FYI @deldesir is investigating:

The 5 apt installs above and the 2 additions to `requirements.txt` for pip (in the PR below) are somehow not enough:

- PR #13 

RECAP: Functional testing still fails on Ubuntu 22.04 (Python 3.10) and 23.10 (Python 3.11) pre-releases, with http://box/books showing **502 Bad Gateway**.

**Comment by deldesir** [comment]
The error was due to the regex from /cps/dep_check.py not matching the format of "pillow" dependency line mistakenly added, even though there was the other correct "Pillow>=10.0.0" dependency. I didn't add the version specification for "pillow". Now this is resolved with its removal.

**Comment by holta** [comment]
> The error was due to the regex from /cps/dep_check.py not matching the format of "pillow" dependency line mistakenly added, even though there was the other correct "Pillow>=10.0.0" dependency.

Great news that PR #14 coincidentally fixed the bug introduced by PR #13 ✅

Root cause explained below...

> FWIW version is not required by https://pip.pypa.io/en/stable/reference/requirements-file-format/

> [BUT] calibre-web makes version specification mandatory with [its] custom dependency check:
https://github.com/deldesir/calibre-web/blob/b453ddc76582944c9ea406fafb4e5e7eec764ca3/cps/dep_check.py#L59

**Comment by holta** [comment]
Basic `pip` tips posted:

- https://github.com/iiab/iiab/commit/64cdb3869c09b3ac0495faa810b72fb71e774dcc

Lesson Learned — to avoid Dependency Hell:

Critical stuff like `requirements.txt` needs **actual testing** prior to merging _and/or_ a 2nd set of eyes too (i.e. actual human reviewer!)

**Pull request merged**
